# Example configuration for headless Camunda deployment
# This configuration disables all secondary storage components

camunda:
  database:
    type: none
    # The schema-manager.createSchema will be automatically set to false
    # when database.type=none, but you can also set it explicitly:
    # schema-manager:
    #   createSchema: false

# Zeebe broker configuration (engine-only mode)
zeebe:
  broker:
    gateway:
      enable: true
      network:
        port: 26500
    network:
      host: 0.0.0.0
      port: 26501
    cluster:
      nodeId: 0
      partitionsCount: 1
      replicationFactor: 1
      clusterSize: 1

# Spring configuration - only enable broker profile
spring:
  profiles:
    active: broker
