---
name: Build Frontend

# owner: @camunda/monorepo-devops-team

description: Builds the frontend project in a certain Yarn workspace

inputs:
  node-version:
    description: The Node.js version to use
    required: false
    default: "20"
  directory:
    description: Directory of the Yarn workspace to build
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install node dependencies
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: npm ci

    - name: Build frontend
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: npm run build
