# description: Workflow that runs the backup restore tests for Operate
# test location: operate/qa/backup-restore-tests
# type: CI
# owner: @camunda/data-layer
name: Operate Run Test Backup/Restore
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
jobs:
  run-backup-restore-tests:
    uses: ./.github/workflows/operate-run-tests.yml
    with:
      command: ./mvnw -B -pl operate/qa/backup-restore-tests -DskipChecks -P -docker,-skipTests verify
    secrets: inherit
