# description: Visual regression tests for Operate
# test location: operate/client/e2e-playwright
# type: CI
# owner: @camunda/core-features
name: "Operate / Visual Regression Tests"
on:
  workflow_call: {}

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}', github.workflow, github.ref == 'refs/heads/main' && github.sha || github.ref) }}

jobs:
  test:
    runs-on: gcp-core-2-default
    container:
      image: mcr.microsoft.com/playwright:v1.53.1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install node dependencies
        working-directory: ./operate/client
        run: yarn
      - name: Build frontend
        working-directory: ./operate/client
        run: yarn build:visual-regression
      - name: Start server
        working-directory: ./operate/client
        run: yarn start:visual-regression &
      - name: Run Playwright tests
        working-directory: ./operate/client
        run: yarn test:visual
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Playwright report
          path: operate/client/playwright-report/
          retention-days: 30

      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
