# description: Runs the CI tests owned by Identity. Runs unit tests
# test location: operate/webapp
# owner: Identity
---
name: Operate Identity CI
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'stable/**'
      - 'release**'
    paths:
      - '.ci/**'
      - '.github/actions/**'
      - '.github/workflows/operate-*'
      - 'bom/*'
      - 'operate.Dockerfile'
      - 'operate/**'
      - 'parent/*'
      - 'pom.xml'
      - 'webapps-common/**'
  pull_request:
    paths:
      - '.ci/**'
      - '.github/actions/**'
      - '.github/workflows/operate-*'
      - 'bom/*'
      - 'operate/**'
      - 'pom.xml'
      - 'operate.Dockerfile'
      - 'parent/*'
      - 'webapps-common/**'
permissions:
  contents: read

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}', github.workflow, github.ref == 'refs/heads/main' && github.sha || github.ref) }}

jobs:
  run-identity-unit-tests:
    name: Operate Backend Unit Tests - Identity
    uses: ./.github/workflows/operate-ci-test-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      command: ./mvnw -f operate verify -T1C -B -P skipFrontendBuild -DskipITs -DskipCoreFeaturesUTs -DskipDataLayerUTs -DskipDockerProfile -DskipChecks
      test-type: Unit Tests
      runner-type: gcp-core-4-default
