name: Test Release E2E Workflow

on:
  workflow_dispatch:
    inputs:
      monorepo_release:
        description: "Test version (e.g., 8.8.0)"
        required: true
        type: string

jobs:
  test-logic:
    runs-on: ubuntu-latest
    steps:
      - name: Test version parsing
        run: |
          release_version="${{ github.event.inputs.monorepo_release }}"
          echo "Release version: $release_version"
          
          # Validate version format
          if [[ ! "$release_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Invalid version format"
            exit 1
          fi
          echo "✅ Version format valid"
          
          # Test base branch detection
          major_minor=$(echo "$release_version" | cut -d. -f1-2)
          echo "Major.minor: $major_minor"
          
          if [[ "$major_minor" == "8.6" ]]; then
            base="stable/8.6"
          elif [[ "$major_minor" == "8.7" ]]; then
            base="stable/8.7"
          elif [[ "$major_minor" == "8.8" ]]; then
            base="stable/8.8"
          else
            base="main"
          fi
          
          echo "✅ Detected base branch: $base"
          
      - uses: actions/checkout@v4
      
      - name: Test docker-compose detection
        run: |
          base="stable/8.7"  # Simulate detected base
          if [[ "$base" == "stable/8.6" || "$base" == "stable/8.7" ]]; then
            echo "✅ Would use separate services (zeebe, tasklist, operate)"
          else
            echo "✅ Would use unified camunda service"
          fi